baseURL = "https://example.com/"
canonifyurls = true
copyright = "Sebastian Pech"
enableRobotsTXT = true
ignoreFiles = ["content/portfolio/\\.*", "content/product/\\.*", "content/sketch/\\.*", "content/homepage/\\.*", "content/post/\\.*", "content/\\.*"]
languageCode = "en-US"
paginate = 5
pygmentsCodeFences = true
theme = "bootstrap-bp-hugo-startpage"
title = "Bootstrap-BP hugo startpage"
[Author]
name = "Sebastian Pech"
[[menu.main]]
name = "Midvale"
parent = "tutorials"
url = "https://darksky.net/forecast/40.6139,-111.8878/us12/en"
weight = 4
[[menu.main]]
name = "Dexter"
url = "https://darksky.net/forecast/44.0057,-76.0439/us12/en"
weight = 3
[[menu.main]]
name = "Original Songs - JW"
url = "https://www.jw.org/en/library/music-songs/original-songs/safeguard-your-mind/"
weight = 2
[[menu.main]]
name = "What's New? - JW"
parent = "tutorials"
url = "https://www.jw.org/en/whats-new/"
weight = 1
[params]
description = "Text about the site"
startPageColumns = true
welcomeText = "Bootstrap-BP hugo startpage"
[[params.searchEngines]]
activated = true
name = "Google"
url = "https://www.google.com/search"
[[params.searchEngines]]
activated = true
name = "DuckDuckGo"
url = "https://duckduckgo.com/"
[[params.searchEngines]]
activated = true
name = "Bing"
url = "https://www.bing.com/search"
[[params.searchEngines]]
activated = true
name = "Baidu"
searchkey = "wd"
url = "https://baidu.com/s"
[permalinks]
page = "/:slug/"
pages = "/:slug/"
post = "/:year/:month/:slug/"
posts = "/:year/:month/:slug/"
[sitemap]
changefreq = "weekly"
priority = 0.5
[taxonomies]
